//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkModelServiceLibrary {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class ServicePorts : global::System.Configuration.ApplicationSettingsBase {
        
        private static ServicePorts defaultInstance = ((ServicePorts)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ServicePorts())));
        
        public static ServicePorts Default {
            get {
                return defaultInstance;
            }
        }
    }
}
